// Datos de la "parte 2" del catálogo, desde Documents/kinara/Laura2.xlsx (ver tasks/018-catalogo-parte-2.md).
// El Excel solo trae nombre/modelo/color/stock por talla — sin precio ni descripción.
// copySource indica que kind/descripción/materiales son un borrador de Claude, pendiente
// de aprobación del usuario (mismo patrón que scripts/seed-data.ts).
export type SeedVariantParte2 = {
  name: string;
  hex: string;
  stock: { S: number; M: number; L: number; XL: number };
};

export type SeedProductParte2 = {
  /** Si ya existe un producto con este nombre (ej. YUCA BRA), se completa en vez de crear uno nuevo. */
  existingProductId?: string;
  slug: string;
  name: string;
  category: "mujer" | "hombre" | "accesorios";
  kind: string;
  modelo: string;
  description: string;
  materials: string;
  copySource: "claude_draft_approved";
  colors: SeedVariantParte2[];
};

export const SEED_PRODUCTS_PARTE2: SeedProductParte2[] = [
  {
    existingProductId: "njdfsa9b",
    slug: "yuca-bra",
    name: "YUCA BRA",
    category: "mujer",
    kind: "Top",
    modelo: "JV-028",
    description: "Bra deportivo con espalda cruzada.",
    materials: "Tela suave y compresiva. Soporte medio. Ideal para yoga y uso diario.",
    copySource: "claude_draft_approved",
    colors: [
      { name: "Negro", hex: "#1D1C1C", stock: { S: 2, M: 4, L: 4, XL: 0 } },
      { name: "Ivory", hex: "#D8D2CD", stock: { S: 2, M: 4, L: 4, XL: 0 } },
      { name: "Verde Claro", hex: "#A8C9A0", stock: { S: 2, M: 4, L: 4, XL: 0 } },
      { name: "Rosa", hex: "#F0C2E1", stock: { S: 2, M: 4, L: 4, XL: 0 } },
    ],
  },
  {
    slug: "leggin-felpada",
    name: "LEGGIN FELPADA",
    category: "mujer",
    kind: "Legging",
    modelo: "JV-FELPADA002",
    description: "Legging afelpado por dentro, ideal para clima frío.",
    materials: "Interior afelpado y cálido. Exterior elástico que moldea la figura. Cintura alta. Ideal para invierno y actividades al aire libre.",
    copySource: "claude_draft_approved",
    colors: [
      { name: "Marino", hex: "#2B3955", stock: { S: 2, M: 2, L: 2, XL: 2 } },
      { name: "Gris", hex: "#676965", stock: { S: 2, M: 2, L: 2, XL: 2 } },
      { name: "Café", hex: "#9E7B61", stock: { S: 2, M: 2, L: 2, XL: 2 } },
      { name: "Negro", hex: "#1D1C1C", stock: { S: 2, M: 2, L: 2, XL: 2 } },
      { name: "Olivo", hex: "#6B6B47", stock: { S: 2, M: 2, L: 2, XL: 2 } },
    ],
  },
  {
    slug: "wrinkle-short",
    name: "WRINKLE SHORT",
    category: "mujer",
    kind: "Bottom",
    modelo: "JV072",
    description: "Short deportivo con textura arrugada (wrinkle).",
    materials: "Tela con textura crinkle transpirable. Secado rápido. Cómodo y flexible. Ideal para entrenar o uso casual.",
    copySource: "claude_draft_approved",
    colors: [
      { name: "Negro", hex: "#1D1C1C", stock: { S: 3, M: 3, L: 3, XL: 0 } },
      { name: "Cocoa", hex: "#A3866E", stock: { S: 3, M: 3, L: 3, XL: 0 } },
      { name: "Rosa", hex: "#F0C2E1", stock: { S: 3, M: 3, L: 3, XL: 0 } },
      { name: "Lila", hex: "#B093BB", stock: { S: 3, M: 3, L: 3, XL: 0 } },
      { name: "Agua Blue", hex: "#7FB8C4", stock: { S: 3, M: 3, L: 3, XL: 0 } },
    ],
  },
  {
    slug: "essential-shirt",
    name: "ESSENTIAL SHIRT",
    category: "mujer",
    kind: "Top",
    modelo: "4322",
    description: "Playera esencial de corte relajado.",
    materials: "Tela suave de uso diario. Corte relajado. Fácil de combinar. Transpirable.",
    copySource: "claude_draft_approved",
    colors: [
      { name: "Negro", hex: "#1D1C1C", stock: { S: 2, M: 2, L: 2, XL: 0 } },
      { name: "Blanco", hex: "#F0F0F0", stock: { S: 2, M: 2, L: 2, XL: 0 } },
      { name: "Azul Gris", hex: "#A7AEC1", stock: { S: 2, M: 2, L: 2, XL: 0 } },
      { name: "Marino", hex: "#2B3955", stock: { S: 2, M: 2, L: 2, XL: 0 } },
      { name: "Palo De Rosa", hex: "#E7C6D8", stock: { S: 2, M: 2, L: 2, XL: 0 } },
      { name: "Vino", hex: "#772836", stock: { S: 2, M: 2, L: 2, XL: 0 } },
      { name: "Botella", hex: "#2F4F3E", stock: { S: 2, M: 2, L: 2, XL: 0 } },
      { name: "Lila", hex: "#B093BB", stock: { S: 2, M: 2, L: 2, XL: 0 } },
    ],
  },
  {
    slug: "seatle-top",
    name: "SEATLE TOP",
    category: "mujer",
    kind: "Top",
    modelo: "2311",
    description: "Top deportivo básico de tirantes.",
    materials: "Tela suave y elástica. Ajuste cómodo. Ideal para entrenar o uso casual.",
    copySource: "claude_draft_approved",
    colors: [
      { name: "Rojo", hex: "#9E0429", stock: { S: 2, M: 2, L: 2, XL: 0 } },
      { name: "Rosa", hex: "#F0C2E1", stock: { S: 2, M: 2, L: 2, XL: 0 } },
      { name: "Botella", hex: "#2F4F3E", stock: { S: 2, M: 2, L: 2, XL: 0 } },
      { name: "Vino", hex: "#772836", stock: { S: 2, M: 2, L: 2, XL: 0 } },
      { name: "Rey", hex: "#282A59", stock: { S: 2, M: 2, L: 2, XL: 0 } },
      { name: "Negro", hex: "#1D1C1C", stock: { S: 0, M: 2, L: 2, XL: 0 } },
      { name: "Blanco", hex: "#F0F0F0", stock: { S: 2, M: 2, L: 2, XL: 0 } },
    ],
  },
  {
    slug: "conjunto-camuflaje",
    name: "CONJUNTO CAMUFLAJE",
    category: "mujer",
    kind: "Set",
    modelo: "0522",
    description: "Conjunto deportivo estampado camuflaje.",
    materials: "Tela elástica de secado rápido. Estampado camuflaje. Ideal para entrenar o uso casual.",
    copySource: "claude_draft_approved",
    colors: [
      { name: "Militar", hex: "#5A5D46", stock: { S: 2, M: 2, L: 0, XL: 0 } },
      { name: "Turquesa", hex: "#30BFBF", stock: { S: 2, M: 2, L: 2, XL: 0 } },
      { name: "Lila", hex: "#B093BB", stock: { S: 2, M: 2, L: 2, XL: 0 } },
      { name: "Rosa", hex: "#F0C2E1", stock: { S: 2, M: 2, L: 2, XL: 0 } },
    ],
  },
  {
    slug: "conjunto-mesh",
    name: "CONJUNTO MESH",
    category: "mujer",
    kind: "Set",
    modelo: "0508",
    description: "Conjunto deportivo con detalles de malla (mesh).",
    materials: "Paneles de malla transpirable. Tela elástica que moldea la figura. Ideal para entrenar.",
    copySource: "claude_draft_approved",
    colors: [
      { name: "Rosa", hex: "#F0C2E1", stock: { S: 2, M: 2, L: 2, XL: 0 } },
      { name: "Negro", hex: "#1D1C1C", stock: { S: 2, M: 2, L: 2, XL: 0 } },
      { name: "Mulberry", hex: "#72235C", stock: { S: 2, M: 2, L: 2, XL: 0 } },
    ],
  },
  {
    slug: "bottee-set",
    name: "BOTTEE SET",
    category: "mujer",
    kind: "Set",
    modelo: "0408",
    description: "Conjunto deportivo de top y short.",
    materials: "Tela suave y elástica. Ajuste cómodo. Ideal para yoga o uso casual.",
    copySource: "claude_draft_approved",
    colors: [
      { name: "Verde Fresco", hex: "#C5D9C0", stock: { S: 2, M: 2, L: 2, XL: 0 } },
      { name: "Rosa", hex: "#F0C2E1", stock: { S: 1, M: 2, L: 2, XL: 0 } },
      { name: "Violet", hex: "#8A6FB0", stock: { S: 2, M: 2, L: 2, XL: 0 } },
    ],
  },
  {
    slug: "enterizo-largo",
    name: "ENTERIZO LARGO",
    category: "mujer",
    kind: "Enterizo",
    modelo: "0101",
    description: "Enterizo largo deportivo de una pieza.",
    materials: "Tela elástica que moldea la figura. Ajuste cómodo de pierna larga. Ideal para yoga o uso casual.",
    copySource: "claude_draft_approved",
    colors: [
      { name: "Rojo", hex: "#9E0429", stock: { S: 1, M: 0, L: 0, XL: 0 } },
      { name: "Rey", hex: "#282A59", stock: { S: 0, M: 0, L: 3, XL: 0 } },
      { name: "Oxford", hex: "#3B3F47", stock: { S: 0, M: 0, L: 7, XL: 0 } },
    ],
  },
  {
    slug: "leisure-pants",
    name: "LEISURE PANTS",
    category: "mujer",
    kind: "Bottom",
    modelo: "2603",
    description: "Pantalón deportivo de corte relajado.",
    materials: "Tela suave de uso diario. Corte relajado. Cintura elástica cómoda. Ideal para descanso o uso casual.",
    copySource: "claude_draft_approved",
    colors: [
      { name: "Negro", hex: "#1D1C1C", stock: { S: 3, M: 3, L: 2, XL: 0 } },
      { name: "Marino", hex: "#2B3955", stock: { S: 3, M: 3, L: 2, XL: 0 } },
      { name: "Blanco", hex: "#F0F0F0", stock: { S: 3, M: 3, L: 2, XL: 0 } },
      { name: "Palo De Rosa", hex: "#E7C6D8", stock: { S: 3, M: 3, L: 2, XL: 0 } },
    ],
  },
  {
    slug: "bi-color-set",
    name: "BI COLOR SET",
    category: "mujer",
    kind: "Set",
    modelo: "2421",
    description: "Conjunto deportivo bicolor.",
    materials: "Tela elástica que moldea la figura. Combinación de dos tonos. Ideal para entrenar o uso casual.",
    copySource: "claude_draft_approved",
    colors: [
      { name: "Menta", hex: "#A8D8C8", stock: { S: 0, M: 3, L: 2, XL: 0 } },
      { name: "Negro", hex: "#1D1C1C", stock: { S: 3, M: 3, L: 2, XL: 0 } },
      { name: "Azul Gris", hex: "#A7AEC1", stock: { S: 3, M: 3, L: 2, XL: 0 } },
      { name: "Rosa", hex: "#F0C2E1", stock: { S: 3, M: 3, L: 2, XL: 0 } },
    ],
  },
  {
    slug: "zipper-falda",
    name: "ZIPPER FALDA",
    category: "mujer",
    kind: "Bottom",
    modelo: "2418",
    description: "Vestido deportivo tipo tenis con zíper frontal y falda integrada.",
    materials: "Tela elástica y transpirable. Falda con vuelo integrada. Zíper frontal decorativo. Ideal para tenis o uso casual.",
    copySource: "claude_draft_approved",
    colors: [
      { name: "Negro", hex: "#1D1C1C", stock: { S: 2, M: 2, L: 2, XL: 0 } },
      { name: "Fresa", hex: "#A66966", stock: { S: 2, M: 2, L: 2, XL: 0 } },
      { name: "Mulberry", hex: "#72235C", stock: { S: 2, M: 2, L: 2, XL: 0 } },
      { name: "Rey", hex: "#282A59", stock: { S: 2, M: 2, L: 2, XL: 0 } },
    ],
  },
  {
    slug: "conjunto-bi-color-short",
    name: "CONJUNTO BI COLOR SHORT",
    category: "mujer",
    kind: "Set",
    modelo: "2504",
    description: "Conjunto deportivo bicolor de top y short.",
    materials: "Tela elástica que moldea la figura. Combinación de dos tonos. Ideal para entrenar.",
    copySource: "claude_draft_approved",
    colors: [
      { name: "Magenta", hex: "#C2185B", stock: { S: 0, M: 3, L: 2, XL: 0 } },
      { name: "Negro", hex: "#1D1C1C", stock: { S: 3, M: 3, L: 2, XL: 0 } },
      { name: "Turquesa", hex: "#30BFBF", stock: { S: 3, M: 3, L: 2, XL: 0 } },
    ],
  },
  {
    slug: "newyork-leggin",
    name: "NEWYORKLEGGIN",
    category: "mujer",
    kind: "Legging",
    modelo: "JV031",
    description: "Legging de tiro alto.",
    materials: "Ajuste perfecto que moldea la figura. No transparenta. Tela elástica. Ideal para yoga o uso diario.",
    copySource: "claude_draft_approved",
    colors: [
      { name: "Cocoa", hex: "#A3866E", stock: { S: 3, M: 3, L: 2, XL: 0 } },
      { name: "Gris", hex: "#676965", stock: { S: 3, M: 3, L: 2, XL: 0 } },
      { name: "Marino", hex: "#2B3955", stock: { S: 3, M: 3, L: 2, XL: 0 } },
    ],
  },
  {
    slug: "newyork-top",
    name: "NEWYORK TOP",
    category: "mujer",
    kind: "Top",
    modelo: "JV030",
    description: "Top deportivo a conjunto con New York Leggin.",
    materials: "Tela suave y elástica. Ajuste cómodo. Ideal para entrenar o uso diario.",
    copySource: "claude_draft_approved",
    colors: [
      { name: "Ivory", hex: "#D8D2CD", stock: { S: 3, M: 3, L: 2, XL: 0 } },
      { name: "Verde", hex: "#4C7A5E", stock: { S: 3, M: 3, L: 2, XL: 0 } },
      { name: "Azul Gris", hex: "#A7AEC1", stock: { S: 3, M: 3, L: 2, XL: 0 } },
    ],
  },
  {
    slug: "soft-flare",
    name: "SOFT FLARE",
    category: "mujer",
    kind: "Legging",
    modelo: "JV228",
    description: "Legging acampanado (flare).",
    materials: "Tela suave y elástica. Corte acampanado que estiliza la figura. Ideal para yoga o baile.",
    copySource: "claude_draft_approved",
    colors: [
      { name: "Negro", hex: "#1D1C1C", stock: { S: 5, M: 5, L: 2, XL: 0 } },
      { name: "Ivory", hex: "#D8D2CD", stock: { S: 5, M: 5, L: 2, XL: 0 } },
      { name: "Café", hex: "#9E7B61", stock: { S: 5, M: 5, L: 2, XL: 0 } },
    ],
  },
  {
    slug: "all-out-pants",
    name: "ALL OUT PANTS",
    category: "mujer",
    kind: "Bottom",
    modelo: "2511",
    description: "Pantalón deportivo de corte recto.",
    materials: "Tela cómoda y flexible. Corte recto. Cintura elástica. Ideal para entrenar o uso casual.",
    copySource: "claude_draft_approved",
    colors: [
      { name: "Negro", hex: "#1D1C1C", stock: { S: 5, M: 5, L: 2, XL: 0 } },
      { name: "Gris", hex: "#676965", stock: { S: 5, M: 5, L: 2, XL: 0 } },
      { name: "Marino", hex: "#2B3955", stock: { S: 5, M: 5, L: 2, XL: 0 } },
      { name: "Palo De Rosa", hex: "#E7C6D8", stock: { S: 5, M: 5, L: 2, XL: 0 } },
    ],
  },
  {
    slug: "leggin-flare",
    name: "LEGGIN FLARE",
    category: "mujer",
    kind: "Legging",
    modelo: "2304",
    description: "Legging acampanado (flare).",
    materials: "Tela elástica y compresiva. Corte acampanado que estiliza la figura. Cintura alta. Ideal para yoga o baile.",
    copySource: "claude_draft_approved",
    colors: [
      { name: "Vino", hex: "#772836", stock: { S: 0, M: 3, L: 0, XL: 0 } },
      { name: "Negro", hex: "#1D1C1C", stock: { S: 3, M: 3, L: 2, XL: 0 } },
      { name: "Azul Gris", hex: "#A7AEC1", stock: { S: 3, M: 3, L: 2, XL: 0 } },
      { name: "Lila Griseado", hex: "#9C90A8", stock: { S: 3, M: 3, L: 2, XL: 0 } },
      { name: "Oxford", hex: "#3B3F47", stock: { S: 3, M: 3, L: 2, XL: 0 } },
      { name: "Marino", hex: "#2B3955", stock: { S: 3, M: 3, L: 2, XL: 0 } },
      { name: "Café", hex: "#9E7B61", stock: { S: 3, M: 3, L: 2, XL: 0 } },
    ],
  },
  {
    slug: "set-essental",
    name: "SET ESSENTAL",
    category: "mujer",
    kind: "Set",
    modelo: "JV019+002",
    description: "Conjunto deportivo esencial de top y legging.",
    materials: "Tela suave y elástica. Ajuste cómodo. Ideal para yoga, pilates o uso diario.",
    copySource: "claude_draft_approved",
    colors: [
      { name: "Negro", hex: "#1D1C1C", stock: { S: 2, M: 2, L: 2, XL: 2 } },
      { name: "Palo De Rosa", hex: "#E7C6D8", stock: { S: 2, M: 2, L: 2, XL: 2 } },
      { name: "Marino", hex: "#2B3955", stock: { S: 2, M: 2, L: 2, XL: 2 } },
      { name: "Azul Gris", hex: "#A7AEC1", stock: { S: 2, M: 2, L: 2, XL: 2 } },
      { name: "Vino", hex: "#772836", stock: { S: 2, M: 2, L: 2, XL: 2 } },
      { name: "Ivory", hex: "#D8D2CD", stock: { S: 2, M: 2, L: 2, XL: 2 } },
      { name: "Agua", hex: "#B8D8DC", stock: { S: 2, M: 2, L: 2, XL: 2 } },
    ],
  },
  {
    slug: "conjunto-rib",
    name: "CONJUNTO RIB",
    category: "mujer",
    kind: "Set",
    modelo: "2312+2512",
    description: "Conjunto deportivo de tela acanalada (rib).",
    materials: "Tela acanalada suave y elástica. Ajuste ceñido que moldea la figura. Ideal para uso diario.",
    copySource: "claude_draft_approved",
    colors: [
      { name: "Negro", hex: "#1D1C1C", stock: { S: 0, M: 3, L: 3, XL: 0 } },
      { name: "Blanco", hex: "#F0F0F0", stock: { S: 0, M: 3, L: 3, XL: 0 } },
      { name: "Rosa", hex: "#F0C2E1", stock: { S: 0, M: 3, L: 3, XL: 0 } },
    ],
  },
  {
    slug: "seamless-softess",
    name: "SEAMLESS SOFTESS",
    category: "mujer",
    kind: "Set",
    modelo: "JV001+018",
    description: "Conjunto deportivo sin costuras (seamless).",
    materials: "Tela sin costuras ultra suave. Compresión ligera. Ideal para yoga, pilates o entrenamiento.",
    copySource: "claude_draft_approved",
    colors: [
      { name: "Agua", hex: "#B8D8DC", stock: { S: 0, M: 3, L: 3, XL: 0 } },
      { name: "Morado", hex: "#6A4C93", stock: { S: 3, M: 3, L: 0, XL: 0 } },
      { name: "Azul Gris", hex: "#A7AEC1", stock: { S: 1, M: 3, L: 0, XL: 0 } },
      { name: "Lila", hex: "#B093BB", stock: { S: 0, M: 3, L: 1, XL: 0 } },
      { name: "Palo De Rosa", hex: "#E7C6D8", stock: { S: 2, M: 3, L: 0, XL: 0 } },
      { name: "Ivory", hex: "#D8D2CD", stock: { S: 3, M: 0, L: 3, XL: 0 } },
      { name: "Gris", hex: "#676965", stock: { S: 2, M: 3, L: 0, XL: 0 } },
      { name: "Vino", hex: "#772836", stock: { S: 1, M: 3, L: 0, XL: 0 } },
    ],
  },
  {
    slug: "button",
    name: "BUTTON",
    category: "mujer",
    kind: "Enterizo",
    modelo: "1022",
    description: "Enterizo corto con botonadura frontal tipo camisero.",
    materials: "Tela suave y ligera. Cuello camisero con botones frontales. Corte corto tipo romper. Fácil de combinar.",
    copySource: "claude_draft_approved",
    colors: [
      { name: "Negro", hex: "#1D1C1C", stock: { S: 3, M: 0, L: 3, XL: 0 } },
      { name: "Lila", hex: "#B093BB", stock: { S: 0, M: 3, L: 0, XL: 0 } },
    ],
  },
];
