// Generado a partir de Documents/kinara/Laura Spreadsheet.xlsx + metadata existente en app/data/products.ts.
// copySource indica si la descripción/especificaciones vienen del Excel original o son un borrador
// redactado por Claude y aprobado por el usuario (ver tasks/006-supabase-productos.md).
export type SeedVariant = {
  name: string;
  hex: string;
  stock: { S: number; M: number; L: number; XL: number };
};

export type SeedProduct = {
  id: string;
  slug: string;
  name: string;
  category: "mujer" | "hombre" | "accesorios";
  kind: string;
  price: number;
  description: string;
  materials: string;
  badge: string | null;
  isNew: boolean;
  isBestseller: boolean;
  localImage: string;
  colors: SeedVariant[];
  sizes: string[];
  copySource: "excel" | "claude_draft_approved";
};

export const SEED_PRODUCTS: SeedProduct[] = [
  {
    id: "3322",
    slug: "daily-top",
    name: "DAILY TOP",
    category: "mujer",
    kind: "Top deportivo",
    price: 390.0,
    description: "Crop Top de tirante con cuello en V.",
    materials: "Cómodo con sujetador interior sin aro (almohadillas removibles). Sensación suave. Doble forro. Buena transpiración. Tela ligera.",
    badge: "Nuevo",
    isNew: true,
    isBestseller: false,
    localImage: "/productos/producto_0.png",
    copySource: "excel",
    sizes: ["S", "M", "L"],
    colors: [
      { name: "Negro", hex: "#000000", stock: { S: 2, M: 2, L: 2, XL: 0 } },
      { name: "Blanco", hex: "#FFFFFF", stock: { S: 2, M: 2, L: 2, XL: 0 } },
      { name: "Vino", hex: "#722F37", stock: { S: 2, M: 2, L: 2, XL: 0 } },
      { name: "Rosa", hex: "#FFB6C1", stock: { S: 2, M: 2, L: 2, XL: 0 } },
    ],
  },
  {
    id: "0605",
    slug: "airlift-short",
    name: "AIRLIFT SHORT",
    category: "mujer",
    kind: "Short deportivo",
    price: 390.0,
    description: "Short tiro alto.",
    materials: "Se ajusta y moldea tu figura. Diseño posterior rn V para estilizar tu figura. Cómodo. Resistente. Secado rápido.",
    badge: "Nuevo",
    isNew: true,
    isBestseller: false,
    localImage: "/productos/producto_1.png",
    copySource: "excel",
    sizes: ["M", "L"],
    colors: [
      { name: "Ivory", hex: "#FFFFF0", stock: { S: 0, M: 2, L: 2, XL: 0 } },
      { name: "Rey", hex: "#4169E1", stock: { S: 0, M: 2, L: 2, XL: 0 } },
      { name: "Lila", hex: "#C8A2C8", stock: { S: 0, M: 2, L: 0, XL: 0 } },
      { name: "Marino", hex: "#000080", stock: { S: 0, M: 2, L: 2, XL: 0 } },
      { name: "Negro", hex: "#000000", stock: { S: 0, M: 2, L: 2, XL: 0 } },
    ],
  },
  {
    id: "080924",
    slug: "lulu-top",
    name: "LULU TOP",
    category: "mujer",
    kind: "Top",
    price: 399.0,
    // Descripción original del Excel ("Crop top de manga corta y cuello redondo") no coincidía
    // con la foto real del producto (bra deportivo). Corregido el 2026-07-13 por decisión del
    // usuario: se mantiene la foto, se ajusta el texto (ver tasks/009-fotos-por-color.md).
    description: "Top deportivo tipo bra con espalda cruzada y escote profundo.",
    materials:
      "Tela suave y compresiva que se ajusta al cuerpo. Tirantes cruzados en la espalda para mayor soporte y libertad de movimiento. Ideal para yoga, pilates o uso diario.",
    badge: "Nuevo",
    isNew: true,
    isBestseller: false,
    localImage: "/productos/producto_2.png",
    copySource: "claude_draft_approved",
    sizes: ["M", "L"],
    colors: [
      { name: "Hueso", hex: "#F5F5DC", stock: { S: 0, M: 2, L: 2, XL: 0 } },
      { name: "Rey", hex: "#4169E1", stock: { S: 0, M: 2, L: 2, XL: 0 } },
      { name: "Lila", hex: "#C8A2C8", stock: { S: 0, M: 2, L: 0, XL: 0 } },
      { name: "Marino", hex: "#000080", stock: { S: 0, M: 2, L: 2, XL: 0 } },
      { name: "Negro", hex: "#000000", stock: { S: 0, M: 2, L: 2, XL: 0 } },
    ],
  },
  {
    id: "JV001",
    slug: "chaqueta-fit",
    name: "CHAQUETA FIT",
    category: "mujer",
    kind: "Chaqueta",
    price: 450.0,
    description: "Chaqueta deportiva.",
    materials: "Super ajustada y ligera. Tela agradable que se ajusta a tu cuerpo moldeando tu figura. Tela transpirable. Secado rápido. Flexible y resistente.",
    badge: "Nuevo",
    isNew: true,
    isBestseller: false,
    localImage: "/productos/producto_3.png",
    copySource: "excel",
    sizes: ["M", "L", "XL"],
    colors: [
      { name: "Negro", hex: "#000000", stock: { S: 0, M: 8, L: 8, XL: 8 } },
      { name: "Marino", hex: "#000080", stock: { S: 0, M: 4, L: 4, XL: 4 } },
      { name: "P.De Rosa", hex: "#E7C6D8", stock: { S: 0, M: 4, L: 4, XL: 4 } },
      { name: "Café", hex: "#6F4E37", stock: { S: 0, M: 4, L: 4, XL: 4 } },
      { name: "Azulgris", hex: "#778899", stock: { S: 0, M: 4, L: 4, XL: 4 } },
      { name: "Lila", hex: "#C8A2C8", stock: { S: 0, M: 4, L: 4, XL: 4 } },
    ],
  },
  {
    id: "080225",
    slug: "tecno-premium",
    name: "TECNO PREMIUM",
    category: "mujer",
    kind: "Top técnico",
    price: 680.0,
    description: "Hoodie deportivo con capucha y corte crop.",
    materials: "Tela premium de secado rápido y tacto suave. Ajuste relajado con puños y dobladillo elástico. Bolsillo tipo canguro. Ideal para entrenar o uso casual.",
    badge: "Nuevo",
    isNew: true,
    isBestseller: false,
    localImage: "/productos/producto_4.png",
    copySource: "claude_draft_approved",
    sizes: ["S", "M", "L"],
    colors: [
      { name: "Negro", hex: "#000000", stock: { S: 2, M: 2, L: 2, XL: 0 } },
      { name: "Blanco", hex: "#FFFFFF", stock: { S: 2, M: 2, L: 2, XL: 0 } },
      { name: "Café", hex: "#6F4E37", stock: { S: 2, M: 2, L: 2, XL: 0 } },
      { name: "Rosa", hex: "#FFB6C1", stock: { S: 2, M: 2, L: 2, XL: 0 } },
    ],
  },
  {
    id: "080624",
    slug: "chamarra-nikka",
    name: "CHAMARRA NIKKA",
    category: "mujer",
    kind: "Chamarra",
    price: 700.0,
    description: "Chamarra deportiva estilo anorak con cuello alto y medio zíper.",
    materials: "Tela cortavientos ligera y resistente al agua. Dobladillo ajustable con jareta. Corte crop oversize. Ideal para actividades al aire libre y uso diario.",
    badge: "Nuevo",
    isNew: true,
    isBestseller: false,
    localImage: "/productos/producto_5.png",
    copySource: "claude_draft_approved",
    sizes: ["S", "M", "L"],
    colors: [
      { name: "Negro", hex: "#000000", stock: { S: 2, M: 2, L: 2, XL: 0 } },
      { name: "Hueso", hex: "#F5F5DC", stock: { S: 2, M: 2, L: 2, XL: 0 } },
      { name: "Rosa", hex: "#FFB6C1", stock: { S: 2, M: 2, L: 2, XL: 0 } },
      { name: "Café", hex: "#6F4E37", stock: { S: 2, M: 2, L: 2, XL: 0 } },
    ],
  },
  {
    id: "2522",
    slug: "bicrossflare",
    name: "BICROSSFLARE",
    category: "mujer",
    kind: "Legging",
    price: 799.0,
    description: "Conjunto deportivo de top y pantalón acampanado con cintura cruzada.",
    materials: "Tela suave y elástica que se ajusta al cuerpo. Corte acampanado (flare) que estiliza la figura. Cintura cruzada cómoda y favorecedora. Ideal para yoga, baile o uso casual.",
    badge: "Nuevo",
    isNew: true,
    isBestseller: false,
    localImage: "/productos/producto_6.png",
    copySource: "claude_draft_approved",
    sizes: ["S", "M", "L"],
    colors: [
      { name: "Negro", hex: "#000000", stock: { S: 2, M: 2, L: 2, XL: 0 } },
      { name: "Marino", hex: "#000080", stock: { S: 2, M: 2, L: 2, XL: 0 } },
      { name: "Cocoa", hex: "#875F42", stock: { S: 2, M: 2, L: 2, XL: 0 } },
      { name: "Gris", hex: "#808080", stock: { S: 2, M: 2, L: 2, XL: 0 } },
      { name: "Azul Gris", hex: "#778899", stock: { S: 2, M: 2, L: 2, XL: 0 } },
      { name: "Verde Fresco", hex: "#90EE90", stock: { S: 2, M: 2, L: 2, XL: 0 } },
      { name: "Rosa", hex: "#FFB6C1", stock: { S: 2, M: 2, L: 2, XL: 0 } },
    ],
  },
  {
    id: "2420",
    slug: "aligh-leggin",
    name: "ALIGH LEGGIN",
    category: "mujer",
    kind: "Legging",
    price: 450.0,
    description: "Legging tiro alto.",
    materials: "Ajuste perfecto y moldea tu cuerpo. No transparenta. Tiene una gran comodida para cualquier tipo de ejercicio o actividad diaria. Tela elástica. Yoga",
    badge: "Nuevo",
    isNew: true,
    isBestseller: false,
    localImage: "/productos/producto_7.png",
    copySource: "excel",
    sizes: ["S", "M", "L"],
    colors: [
      { name: "Negro", hex: "#000000", stock: { S: 2, M: 2, L: 2, XL: 0 } },
      { name: "Rey", hex: "#4169E1", stock: { S: 2, M: 2, L: 2, XL: 0 } },
      { name: "Vino", hex: "#722F37", stock: { S: 2, M: 2, L: 2, XL: 0 } },
    ],
  },
  {
    id: "2509",
    slug: "zipper-bra",
    name: "ZIPPER BRA",
    category: "mujer",
    kind: "Top con zipper",
    price: 499.0,
    description: "Bra deportivo con zipper.",
    materials: "Tiene diseño en la espalda. Con copa removible. Buen ajuste para cualquier deporte.",
    badge: "Nuevo",
    isNew: true,
    isBestseller: false,
    localImage: "/productos/producto_8.png",
    copySource: "excel",
    sizes: ["S", "M", "L"],
    colors: [
      { name: "Negro", hex: "#000000", stock: { S: 2, M: 2, L: 2, XL: 0 } },
      { name: "Rey", hex: "#4169E1", stock: { S: 2, M: 2, L: 2, XL: 0 } },
      { name: "Vino", hex: "#722F37", stock: { S: 2, M: 2, L: 2, XL: 0 } },
    ],
  },
  {
    id: "JV024",
    slug: "lilia-chaqueta",
    name: "LILIA CHAQUETA",
    category: "mujer",
    kind: "Chaqueta",
    price: 550.0,
    description: "Chaqueta deportiva con capucha y cierre completo.",
    materials: "Tela ligera y transpirable de secado rápido. Bolsillos laterales con cierre. Ajuste cómodo para entrenar o uso diario. Resistente y flexible.",
    badge: "Nuevo",
    isNew: true,
    isBestseller: false,
    localImage: "/productos/producto_9.png",
    copySource: "claude_draft_approved",
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Rey", hex: "#4169E1", stock: { S: 2, M: 2, L: 2, XL: 2 } },
      { name: "Negro", hex: "#000000", stock: { S: 2, M: 2, L: 2, XL: 2 } },
    ],
  },
  {
    id: "2315",
    slug: "lulu-top-2315",
    name: "LULU TOP",
    category: "mujer",
    kind: "Top",
    price: 460.0,
    description: "Crop top manga corta. cuello redondo y crote redondo.",
    materials: "Lycra super suave y comoda, se amolda bien a tu cuerpo. Almohadillas removibles. Material transpirable y suave de alta calidad que ayuda a absorver la humedad y el sudor rápidamente. Tiene una banda elástica integrada en el dobladillo que se envuelve mejor alrededor de la parte inferior del pecho y la parte superior de abdomen. Tu mejor opción para yoga, fitness, correr, ciclismo, entrenamiento, pilates, entrenamiento de gimnasio o uso casual.",
    badge: "Nuevo",
    isNew: true,
    isBestseller: false,
    localImage: "/productos/producto_10.png",
    copySource: "excel",
    sizes: ["S", "M", "L"],
    colors: [
      { name: "Lila", hex: "#C8A2C8", stock: { S: 0, M: 0, L: 2, XL: 0 } },
      { name: "Rojo", hex: "#FF0000", stock: { S: 1, M: 0, L: 2, XL: 0 } },
      { name: "P.De Rosa", hex: "#E7C6D8", stock: { S: 1, M: 0, L: 2, XL: 0 } },
      { name: "Negro", hex: "#000000", stock: { S: 0, M: 2, L: 3, XL: 0 } },
      { name: "Rey", hex: "#4169E1", stock: { S: 1, M: 2, L: 2, XL: 0 } },
      { name: "Mulberry", hex: "#C54B8C", stock: { S: 1, M: 2, L: 2, XL: 0 } },
      { name: "Rosafresa", hex: "#FC5A8D", stock: { S: 1, M: 2, L: 2, XL: 0 } },
    ],
  },
  {
    id: "JV014",
    slug: "pastel-falda",
    name: "PASTEL FALDA",
    category: "mujer",
    kind: "Falda",
    price: 499.0,
    description: "Falda Deportiva super ajustable con short.",
    materials: "Incluye bolsillo oculto. Tableado en la parte trasera. Ideal para tenis. Tela trabspirable. Comoda. Uso casual.",
    badge: "Nuevo",
    isNew: true,
    isBestseller: false,
    localImage: "/productos/producto_11.png",
    copySource: "excel",
    sizes: ["S", "M", "L"],
    colors: [
      { name: "Rosa", hex: "#FFB6C1", stock: { S: 2, M: 2, L: 2, XL: 0 } },
      { name: "Negro", hex: "#000000", stock: { S: 2, M: 2, L: 2, XL: 0 } },
      { name: "Blanco", hex: "#FFFFFF", stock: { S: 2, M: 2, L: 2, XL: 0 } },
    ],
  },
  {
    id: "2510",
    slug: "conjunto-nube",
    name: "CONJUNTO NUBE",
    category: "mujer",
    kind: "Conjunto",
    price: 999.0,
    description: "Conjunto deportivo de bra y legging con borde de ondas.",
    materials: "Tela suave tipo \"second-skin\" que moldea la figura. Detalle de borde ondulado en escote y sisas. Cintura alta. Ideal para yoga, pilates y uso casual.",
    badge: "Nuevo",
    isNew: true,
    isBestseller: false,
    localImage: "/productos/producto_12.png",
    copySource: "claude_draft_approved",
    sizes: ["S", "M", "L"],
    colors: [
      { name: "Negro", hex: "#000000", stock: { S: 2, M: 2, L: 2, XL: 0 } },
      { name: "Mulberry", hex: "#C54B8C", stock: { S: 2, M: 2, L: 2, XL: 0 } },
      { name: "Marino", hex: "#000080", stock: { S: 2, M: 2, L: 2, XL: 0 } },
      { name: "Azul Gris", hex: "#778899", stock: { S: 2, M: 2, L: 2, XL: 0 } },
      { name: "Botanica Verde", hex: "#5F8575", stock: { S: 2, M: 2, L: 2, XL: 0 } },
      { name: "Melon", hex: "#FEBAAD", stock: { S: 2, M: 2, L: 2, XL: 0 } },
    ],
  },
  {
    id: "JV002",
    slug: "swift-leggin",
    name: "SWIFT LEGGIN",
    category: "mujer",
    kind: "Legging",
    price: 300.0,
    description: "Leggin deportivo ultra ligero.",
    materials: "Cómodo, resistente y flexible. Para cualquier actividad. Uso diario. Tela trasnpirable. Secado rápido. Resistente.",
    badge: "Nuevo",
    isNew: true,
    isBestseller: false,
    localImage: "/productos/producto_15.png",
    copySource: "excel",
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Negro", hex: "#000000", stock: { S: 4, M: 8, L: 8, XL: 4 } },
      { name: "Marino", hex: "#000080", stock: { S: 2, M: 4, L: 4, XL: 2 } },
      { name: "Vino", hex: "#722F37", stock: { S: 2, M: 4, L: 4, XL: 2 } },
      { name: "P.De Rosa", hex: "#E7C6D8", stock: { S: 2, M: 4, L: 4, XL: 2 } },
      { name: "Café", hex: "#6F4E37", stock: { S: 2, M: 4, L: 4, XL: 2 } },
      { name: "Camel", hex: "#C19A6B", stock: { S: 2, M: 4, L: 4, XL: 2 } },
      { name: "Azul Gris", hex: "#778899", stock: { S: 2, M: 4, L: 4, XL: 2 } },
      { name: "Lila", hex: "#C8A2C8", stock: { S: 2, M: 4, L: 4, XL: 2 } },
    ],
  },
  {
    id: "GZ01",
    slug: "no-limite-short",
    name: "NO LIMITE SHORT",
    category: "mujer",
    kind: "Short",
    price: 499.0,
    description: "Short estilo oversize.",
    materials: "Con jareta ajustable en la cintura. Bolsillos laterales. Alta resistencia. Alta absorción. Adaptabilidad.",
    badge: "Nuevo",
    isNew: true,
    isBestseller: false,
    localImage: "/productos/producto_13.png",
    copySource: "excel",
    sizes: ["S", "M", "L"],
    colors: [
      { name: "Negro", hex: "#000000", stock: { S: 2, M: 2, L: 2, XL: 0 } },
      { name: "Blanco", hex: "#FFFFFF", stock: { S: 2, M: 2, L: 2, XL: 0 } },
    ],
  },
  {
    id: "WY6",
    slug: "accolade-hoodie",
    name: "ACCOLADE HOODIE",
    category: "mujer",
    kind: "Sudadera",
    price: 699.0,
    description: "Hoodie estilo oversize.",
    materials: "Jareta ajustable en la cintura. Bolsillos laterales. Alta resistencia. Alta absorción. Adaptabilidad.",
    badge: "Nuevo",
    isNew: true,
    isBestseller: false,
    localImage: "/productos/producto_14.png",
    copySource: "excel",
    sizes: ["S", "M", "L"],
    colors: [
      { name: "Negro", hex: "#000000", stock: { S: 2, M: 2, L: 2, XL: 0 } },
      { name: "Blanco", hex: "#FFFFFF", stock: { S: 2, M: 2, L: 2, XL: 0 } },
    ],
  },
];
